### ISSUE TITLE
AssemblyFlags引用问题

### ISSUE THREAD

**Issue by BobbyWeaver2015** [ZeroUltra/UnityManualReload#4]
感谢大佬分享，现在用packageManger导入会报下面的错
ManuallyReloadDomainTool.cs(168,57): error CS0104: 'AssemblyFlags' is an ambiguous reference between 'UnityEditor.Compilation.AssemblyFlags' and 'System.Reflection.AssemblyFlags'

**Comment by ZeroUltra** [comment]
> 感谢大佬分享，现在用packageManger导入会报下面的错 ManuallyReloadDomainTool.cs(168,57): error CS0104: 'AssemblyFlags' is an ambiguous reference between 'UnityEditor.Compilation.AssemblyFlags' and 'System.Reflection.AssemblyFlags'

脚本应该没这问题啊
解决你这个问题也简单,引用命名空间的地方添加
`using AssemblyFlags = UnityEditor.Compilation.AssemblyFlags;`

**Comment by ZeroUltra** [comment]
或者下载最新版本
